export const LIKE_PERSON = 'LIKE_PERSON';
export const LIKE_PERSON_SUCCESS = 'LIKE_PERSON_SUCCESS';
export const LIKE_PERSON_ERROR = 'LIKE_PERSON_ERROR';

export const SUPERLIKE_PERSON = 'SUPERLIKE_PERSON';
export const SUPERLIKE_PERSON_SUCCESS = 'SUPERLIKE_PERSON_SUCCESS';
export const SUPERLIKE_PERSON_ERROR = 'SUPERLIKE_PERSON_ERROR';

export const PASS_PERSON = 'PASS_PERSON';
export const PASS_PERSON_SUCCESS = 'PASS_PERSON_SUCCESS';
export const PASS_PERSON_ERROR = 'PASS_PERSON_ERROR';

export const DETAIL_PERSON = 'DETAIL_PERSON';

export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS';
export const FETCH_RECOMMENDATIONS_ERROR = 'FETCH_RECOMMENDATIONS_ERROR';
export const FETCH_RECOMMENDATIONS_LOCALLY = 'FETCH_RECOMMENDATIONS_LOCALLY';
export const SORT_RECOMMENDATIONS = 'SORT_RECOMMENDATIONS';
export const REMOVE_RECOMMENDATION = 'REMOVE_RECOMMENDATION';


export const DUMP_ALL_RECOMMENDATIONS_START = 'DUMP_ALL_RECOMMENDATIONS_START';
export const DUMP_ALL_RECOMMENDATIONS = 'DUMP_ALL_RECOMMENDATIONS';
export const DUMP_ALL_RECOMMENDATIONS_SUCCESS = 'DUMP_ALL_RECOMMENDATIONS_SUCCESS';
