export const LIKE_PERSON = 'LIKE_PERSON';
export const LIKE_PERSON_SUCCESS = 'LIKE_PERSON_SUCCESS';
export const LIKE_PERSON_ERROR = 'LIKE_PERSON_ERROR';

export const SUPERLIKE_PERSON = 'SUPERLIKE_PERSON';
export const SUPERLIKE_PERSON_SUCCESS = 'SUPERLIKE_PERSON_SUCCESS';
export const SUPERLIKE_PERSON_ERROR = 'SUPERLIKE_PERSON_ERROR';

export const PASS_PERSON = 'PASS_PERSON';
export const PASS_PERSON_SUCCESS = 'PASS_PERSON_SUCCESS';
export const PASS_PERSON_ERROR = 'PASS_PERSON_ERROR';

export const DETAIL_PERSON = 'DETAIL_PERSON';
