export const START_EDITING_BIO = 'START_EDITING_BIO';
export const FINSHED_EDITING_BIO = 'FINISHED_EDITING_BIO';
export const BIO_UPDATE_START = 'BIO_UPDATE_START';
export const BIO_UPDATE_SUCCESS = 'BIO_UPDATE_SUCCESS';
export const BIO_UPDATE_FAILED = 'BIO_UPDATE_FAILED';
