export const SELECTING_LOCATION = 'SELECTING_LOCATION';
export const SELECT_LOCATION = 'SELECT_LOCATION';

export const EDITING_BIO = 'EDITING_BIO';
export const REORDER_PHOTOS = 'REORDER_PHOTOS';
export const SET_AGE_FILTER = 'SET_AGE_FILTER';
export const SET_GENDER_FILTER = 'SET_GENDER_FILTER';
export const SET_DISTANCE_FILTER = 'SET_DISTANCE_FILTER';
export const SET_GENDER = 'SET_GENDER';
export const SET_DISCOVER = 'SET_DISCOVER';

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const CLEAR_LOCAL_DATA = 'CLEAR_LOCAL_DATA';
export const CLEAR_LOCAL_DATA_SUCCESS = 'CLEAR_LOCAL_DATA_SUCCESS';
