export const EDITING_BIO = 'EDITING_BIO';
export const REORDER_PHOTOS = 'REORDER_PHOTOS';
export const SELECTING_LOCATION = 'SELECTING_LOCATION';
export const SET_AGE_FILTER = 'SET_AGE_FILTER';
export const SET_DISTANCE_FILTER = 'SET_DISTANCE_FILTER';
