export const GLOBAL_NOTIFICATION_RECEIVED = 'GLOBAL_NOTIFICATION_RECEIVED';
export const GLOBAL_NOTIFICATION_PUSHED = 'GLOBAL_NOTIFICATION_PUSHED';
export const GLOBAL_NOTIFICATION_HANDLED = 'GLOBAL_NOTIFICATION_HANDLED';
export const GLOBAL_NOTIFICATION_ADDED = 'GLOBAL_NOTIFICATION_ADDED';
export const NOTIFICATION_MANUAL_REMOVE = 'NOTIFICATION_MANUAL_REMOVE';
