export const GLOBAL_ERROR_RECEIVED = 'GLOBAL_ERROR_RECEIVED';
export const GLOBAL_ERROR_PUSHED = 'GLOBAL_ERROR_PUSHED';
export const GLOBAL_ERROR_HANDLED = 'GLOBAL_ERROR_HANDLED';
export const GLOBAL_ERROR_ADDED = 'GLOBAL_ERROR_ADDED';
export const ERROR_MANUAL_REMOVE = 'ERROR_MANUAL_REMOVE';
