/*
 *
 * Dashboard constants
 *
 */

export const FETCH_UPDATES = 'FETCH_UPDATES';
export const FETCH_UPDATES_ERROR = 'FETCH_UPDATES_ERROR';
export const FETCH_UPDATES_END = 'FETCH_UPDATES_END';

export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const FETCHED_RECOMMENDATIONS_WITH_PREFS = 'FETCHED_RECOMMENDATIONS_WITH_PREFS';
export const STORE_META_DATA_SUCCESS = 'STORE_META_DATA_SUCCESS';
export const REHYDRATE_MATCHES = 'REHYDRATE_MATCHES';
export const REHYDRATE_MATCHES_SUCCESS = 'REHYDRATE_MATCHES_SUCCESS';
export const REHYDRATE_MATCHES_ERROR = 'REHYDRATE_MATCHES_ERROR';

