/*
 *
 * Dashboard constants
 *
 */

export const FETCH_UPDATES = 'FETCH_UPDATES';
export const FETCH_UPDATES_SUCCESS = 'FETCH_UPDATES_SUCCESS';
export const FETCH_UPDATES_ERROR = 'FETCH_UPDATES_ERROR';
export const FETCH_UPDATES_END = 'FETCH_UPDATES_END';

export const FETCH_TINDER_DATA = 'FETCH_TINDER_DATA';
export const FETCH_TINDER_DATA_SUCCESS = 'FETCH_TINDER_DATA_SUCCESS';
export const FETCH_TINDER_DATA_ERROR = 'FETCH_TINDER_DATA_ERROR';

export const FETCH_MATCHES = 'FETCH_MATCHES';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_ERROR = 'FETCH_MATCHES_ERROR';

export const SORT_MATCHES = 'SORT_MATCHES';
export const REMOVE_MATCH = 'REMOVE_MATCH';
