export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR';

export const LOGIN_CHROME = 'LOGIN_CHROME';
export const LOGIN_CHROME_SUCCESS = 'LOGIN_CHROME_SUCCESS';
export const LOGIN_CHROME_ERROR = 'LOGIN_CHROME_ERROR';

export const LOGIN_LOCAL = 'LOGIN_LOCAL';
export const LOGIN_LOCAL_SUCCESS = 'LOGIN_LOCAL_SUCCESS';

export const CHANGE_LOGIN = 'CHANGE_USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const SET_GLOBALS = 'SET_GLOBALS';
