export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR';

export const LOGIN_LOCAL = 'LOGIN_LOCAL';
export const LOGIN_LOCAL_SUCCESS = 'LOGIN_LOCAL_SUCCESS';

export const CHANGE_LOGIN = 'CHANGE_USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
